- name: mount directories
  ansible.posix.mount:
    src: "{{ item.from }}"
    path: "{{ item.to }}"
    fstype: none 
    opts: bind
    boot: true
    state: mounted
  loop: "{{ mounts }}"
  when: mounts is defined and (item.nfs is not defined or item.nfs | bool == false)

- name: mount nfs directories
  ansible.posix.mount:
    src: "{{ item.from }}"
    path: "{{ item.to }}"
    fstype: nfs 
    opts: rw,sync,hard 
    boot: true
    state: mounted
  loop: "{{ mounts }}"
  when: mounts is defined and item.nfs is defined and item.nfs == true

