ansible_host: psa.in.tum.de
ansible_port: 60202

host_name: vmpsateam02-02

network_interfaces:
  enp0s8:
    name_servers:
      - 192.168.2.1
    dhcp: false
    addresses:
      - 192.168.2.2/24
    routes:
      - to: 192.168.1.0/24
        via: 192.168.2.1
      - to: 192.168.3.0/24
        via: 192.168.2.1
      - to: 192.168.4.0/24
        via: 192.168.2.1
      - to: 192.168.5.0/24
        via: 192.168.2.1
      - to: 192.168.6.0/24
        via: 192.168.2.1
      - to: 192.168.7.0/24
        via: 192.168.2.1
      - to: 192.168.8.0/24
        via: 192.168.2.1
      - to: 192.168.9.0/24
        via: 192.168.2.1
      - to: 192.168.10.0/24
        via: 192.168.2.1

  enp0s3:
    name_servers:
      - 192.168.2.1
    dhcp: true

mounts:
  - to: "/var/lib"
    from: "192.168.2.1:/mnt/raid/vmpsateam02-02/var/lib"
    nfs: true 
  - to: "/var/www"
    from: "192.168.2.1:/mnt/raid/vmpsateam02-02/var/www"
    nfs: true
  - to: "/home.bak"
    from: "192.168.2.1:/mnt/raid/vmpsateam02-02/home.bak"
    nfs: true

