- name: create filesystem
  community.general.filesystem:
    fstype: ext4
    dev: "{{ raid.device }}"

- name: mount filesystem
  ansible.posix.mount:
    path: "{{ raid.mountpoint }}"
    src: "{{ raid.device }}"
    boot: true # Mount on boot.
    state: mounted 
    fstype: ext4

- name: create directories
  ansible.builtin.file:
    path: "{{ raid.mountpoint }}/{{ item }}"
    state: directory
  loop:
    - "vmpsateam02-01"
    - "vmpsateam02-02"

