- name: create filesystem
  community.general.filesystem:
    fstype: ext4
    dev: "{{ raid.device }}"

- name: mount filesystem
  ansible.posix.mount:
    path: "{{ raid.mountpoint }}"
    src: "{{ raid.device }}"
    boot: true # Mount on boot.
    state: mounted 
    fstype: ext4

- name: create directories
  ansible.builtin.file:
    path: "{{ raid.mountpoint }}/{{ item }}"
    state: directory
  loop:
    - "home"
    - "vmpsateam02-01"
    - "vmpsateam02-02"

- name: create home directories for each user
  file:
    path: "{{ raid.mountpoint }}/home/{{ item.name }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: "0755"
  loop: "{{ users.values() | selectattr('name', '!=', 'root') | list }}"

