- import_tasks: dependencies.yml
  tags:
    - raid
    - raid-dependencies

- import_tasks: mdadm.yml
  tags:
    - raid
    - raid-mdadm

- import_tasks: filesystem.yml
  tags:
    - raid
    - raid-filesystem

- import_tasks: nfs.yml
  tags:
    - raid
    - raid-nfs

