- name: restart postfix
  systemd_service:
    name: postfix
    state: restarted

- name: restart dovecot
  systemd_service:
    name: dovecot
    state: restarted

- name: restart clamav
  systemd_service:
    name: clamav-daemon
    state: restarted

- name: restart clamav-freshclam
  systemd_service:
    name: clamav-freshclam
    state: restarted

- name: restart amavis
  shell: "/etc/init.d/amavis restart"

