- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - autoconf
    - gcc
    - libc6
    - make
    - wget
    - unzip
    - apache2
    - php
    - libapache2-mod-php
    - libgd-dev
    - openssl
    - libssl-dev

