- name: install dependencies for plugins
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - autoconf
    - gcc
    - libc6
    - libmcrypt-dev
    - make
    - libssl-dev
    - wget
    - bc
    - gawk
    - dc
    - build-essential
    - snmp
    - libnet-snmp-perl
    - gettext

- name: download plugins
  get_url:
    url: "https://github.com/nagios-plugins/nagios-plugins/archive/release-{{ nagios.plugins_version }}.tar.gz"
    dest: "/tmp/nagios-plugins.tar.gz"

- name: uncompress plugins
  shell:
    cmd: "tar zxf nagios-plugins.tar.gz"
    chdir: "/tmp"

- name: compile and install plugins
  shell:
    cmd: "./tools/setup && ./configure && make && make install"
    chdir: "/tmp/nagios-plugins-release-{{ nagios.plugins_version }}"

- name: download nrpe
  get_url:
    url: "https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-4.1.1/nrpe-4.1.1.tar.gz"
    dest: "/tmp/nrpe.tar.gz"

- name: uncompress nrpe
  shell:
    cmd: "tar zxf nrpe.tar.gz"
    chdir: "/tmp"

- name: compile and install nrpe 
  shell:
    cmd: "./configure && make all && make install-plugin && make install-daemon && make install-init"
    chdir: "/tmp/nrpe-4.1.1" 

