network:
  version: 2
  ethernets:
{% for interface_name, interface in network_interfaces.items() %}
    {{ interface_name }}:
        dhcp4: {{ interface["dhcp"] }}
{% if interface["addresses"] is defined %}
        addresses:
{% for address in interface["addresses"] %}
          - {{ address }}
{% endfor %}
{% endif %}
{% if interface["routes"] is defined %}
        routes:
{% for route in interface["routes"] %}
          - to: {{ route.to }}
            via: {{ route.via }}
{% endfor %}
{% endif %}
{% endfor %}
