- name: add clamav user to amavis group
  user:
    name: clamav
    groups: amavis
    append: true

- name: add amavis user to clamav group
  user:
    name: amavis
    groups: clamav
    append: true

- name: use proxy for freshclam
  lineinfile:
    line: "HTTPProxyServer proxy.cit.tum.de"
    path: /etc/clamav/freshclam.conf
    regexp: "^HTTPProxyServer "

