- name: install postfix
  apt:
    name: postfix
    state: present

- name: install dovecot-core
  apt:
    name: dovecot-core
    state: present

- name: install dovecot-imapd
  apt:
    name: dovecot-imapd
    state: present

- name: install dovecot-pop3d
  apt:
    name: dovecot-pop3d
    state: present

- name: install amavis
  apt:
    name: amavisd-new
    state: present

- name: install clamav
  apt:
    name: clamav-daemon
    state: present

- name: install spamassassin
  apt:
    name: spamassassin
    state: present

