- import_tasks: dependencies.yml
  tags:
    - mail 
    - mail-dependencies

- import_tasks: clamav.yml
  tags:
    - mail
    - mail-clamav
  notify:
    - restart clamav
    - restart clamav-freshclam

- import_tasks: amavis.yml
  tags:
    - mail
    - mail-amavis
  notify: restart amavis

- import_tasks: postfix.yml
  tags:
    - mail 
    - mail-postfix
  notify: restart postfix

- import_tasks: dovecot.yml
  tags:
    - mail
    - mail-dovecot
  notify: restart dovecot

