- import_tasks: nginx-install.yml
  tags:
    - nginx
    - nginx-install

- import_tasks: config.yml
  tags:
    - nginx
    - nginx-config
  notify: reload nginx

- import_tasks: remove-default.yml
  tags:
    - nginx
    - nginx-remove-default
  notify: reload nginx

- import_tasks: logrotate.yml
  tags:
    - nginx
    - nginx-logrotate
