- name: install postgresql
  apt:
    name: postgresql
    state: present

- name: install python pip
  apt:
    name: python3-psycopg2
    state: present

- name: Ensure PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes
